[package]
name = "nebo_cli"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.31.2"
reqwest = "0.9.22"
lazy_static = "1.4.0"
futures = "0.1"